### ISSUE TITLE
Roadmap 2.0

### ISSUE THREAD

**Issue by webketje** [metalsmith/metalsmith-excerpts#43]
This issue regroups and provides an overview of the proposals for 2.0.
Leave a thumbs up if you like all, thumbs down if you don't like any, and a comment if it's somewhere in between.

- [ ] #11 Provide a `truncate` option that takes an instruction string as input `x chars/ words/ sentences/` or `comment` and add an ellipsis at the end `...`.
- [ ] #42 Remove the `multipleFormats` option and make that the default. Add a third format `stripped` which only removes the `outerHTML`
- [ ] #41  Enables to manually indicate the end of the excerpt tag. Variants are:  `<!-- excerpt -->`, `<!-- excerpt:end -->` or could even have an `<!-- excerpt:start -->` too

-
